-- 4 SEO blog articles targeting high-volume Polish beauty keywords
-- Run in Supabase Dashboard → SQL Editor

INSERT INTO blog_posts (title, title_en, title_ru, slug, category, excerpt, excerpt_en, excerpt_ru, author, seo_keywords, content_blocks, is_published, published_at, reading_time_minutes, sort_order)
VALUES

-- 1. "makijaż permanentny brwi Białystok" (1,200 searches/mo)
(
  'Makijaż permanentny brwi w Białymstoku – wszystko, co musisz wiedzieć',
  'Permanent Eyebrow Makeup in Białystok – Everything You Need to Know',
  'Перманентный макияж бровей в Белостоке – всё, что нужно знать',
  'makijaz-permanentny-brwi-bialystok',
  'tips',
  'Planujesz makijaż permanentny brwi w Białymstoku? Dowiedz się o technikach, cenach, pielęgnacji i efektach. Sprawdź, dlaczego warto wybrać salon Katarzyna Brui.',
  'Planning permanent eyebrow makeup in Białystok? Learn about techniques, prices, aftercare and results at Katarzyna Brui salon.',
  'Планируете перманентный макияж бровей в Белостоке? Узнайте о техниках, ценах, уходе и результатах в салоне Katarzyna Brui.',
  'Katarzyna Brui',
  ARRAY['makijaż permanentny brwi Białystok', 'permanentne brwi Białystok', 'microblading brwi Białystok', 'brwi permanentne cena Białystok', 'makijaż permanentny brwi cena', 'ombre brwi Białystok', 'powder brows Białystok'],
  '[
    {"id":"b1-1","type":"heading","level":"h2","text":"Czym jest makijaż permanentny brwi?","text_en":"What is permanent eyebrow makeup?","text_ru":"Что такое перманентный макияж бровей?"},
    {"id":"b1-2","type":"text","text":"Makijaż permanentny brwi to zabieg kosmetyczny polegający na wprowadzeniu pigmentu pod skórę za pomocą specjalnego urządzenia. Efektem są idealnie wymodelowane brwi, które wyglądają naturalnie przez 1–3 lata. W salonie Katarzyna Brui w Białymstoku oferujemy najnowocześniejsze techniki, dopasowane indywidualnie do kształtu twarzy i preferencji każdej klientki.","text_en":"Permanent eyebrow makeup is a cosmetic procedure involving the introduction of pigment under the skin using a specialized device. The result is perfectly shaped brows that look natural for 1–3 years. At Katarzyna Brui salon in Białystok, we offer the latest techniques, individually tailored to each client''s face shape and preferences.","text_ru":"Перманентный макияж бровей — это косметическая процедура, при которой пигмент вводится под кожу с помощью специального аппарата. Результат — идеально смоделированные брови, которые выглядят естественно от 1 до 3 лет. В салоне Katarzyna Brui в Белостоке мы предлагаем самые современные техники, подобранные индивидуально."},
    {"id":"b1-3","type":"heading","level":"h2","text":"Popularne techniki makijażu permanentnego brwi","text_en":"Popular permanent eyebrow techniques","text_ru":"Популярные техники перманентного макияжа бровей"},
    {"id":"b1-4","type":"list","style":"bullet","items":["Microblading – ręczna metoda odwzorowująca pojedyncze włoski. Idealny efekt naturalnych brwi. Cena w Białymstoku: od 600 PLN.","Ombre brows (powder brows) – delikatne cieniowanie dające efekt pudru. Trwałość do 2–3 lat. Cena: od 700 PLN.","Combo brows – połączenie microbladingu i cieniowania. Najlepszy wybór dla osób z rzadkimi brwiami.","Nano brows – wykonywane maszynką, precyzyjne odwzorowanie włosków. Idealne dla skóry tłustej."],"items_en":["Microblading – manual method replicating individual hair strokes. Perfect natural brow effect. Price in Białystok: from 600 PLN.","Ombre brows (powder brows) – gentle shading for a powdered effect. Lasts 2–3 years. Price: from 700 PLN.","Combo brows – combination of microblading and shading. Best choice for sparse brows.","Nano brows – done with a machine for precise hair strokes. Ideal for oily skin."],"items_ru":["Микроблейдинг – ручная техника, воспроизводящая отдельные волоски. Идеальный натуральный эффект. Цена в Белостоке: от 600 PLN.","Омбре брови (пудровые брови) – мягкая растушёвка с эффектом пудры. Держится 2–3 года. Цена: от 700 PLN.","Комбо-брови – сочетание микроблейдинга и растушёвки. Лучший выбор для редких бровей.","Нано-брови – выполняются аппаратом, точное воспроизведение волосков. Идеально для жирной кожи."]},
    {"id":"b1-5","type":"heading","level":"h2","text":"Jak przebiega zabieg w naszym salonie w Białymstoku?","text_en":"How does the procedure work at our Białystok salon?","text_ru":"Как проходит процедура в нашем салоне в Белостоке?"},
    {"id":"b1-6","type":"list","style":"check","items":["Konsultacja – omawiamy oczekiwania, dobieramy kształt i kolor","Rysowanie szkicu – projektujesz brwi razem z linergistką","Znieczulenie – nakładamy krem znieczulający (ok. 20 min)","Pigmentacja – wprowadzanie pigmentu wybraną techniką (60–90 min)","Pielęgnacja – otrzymujesz szczegółowe zalecenia pozabiegowe"],"items_en":["Consultation – we discuss expectations, choose shape and color","Sketch drawing – you design brows together with the artist","Anesthesia – numbing cream applied (approx. 20 min)","Pigmentation – pigment application with chosen technique (60–90 min)","Aftercare – you receive detailed post-treatment instructions"],"items_ru":["Консультация – обсуждаем ожидания, подбираем форму и цвет","Рисование эскиза – вы проектируете брови вместе с мастером","Анестезия – наносим обезболивающий крем (ок. 20 мин)","Пигментация – введение пигмента выбранной техникой (60–90 мин)","Уход – вы получаете подробные рекомендации по уходу"]},
    {"id":"b1-7","type":"heading","level":"h2","text":"Pielęgnacja po zabiegu – jak dbać o brwi?","text_en":"Aftercare – how to take care of your brows?","text_ru":"Уход после процедуры – как ухаживать за бровями?"},
    {"id":"b1-8","type":"text","text":"Pierwsze 7–10 dni po zabiegu to kluczowy okres gojenia. Nie moczmy brwi, unikajmy sauny, solarium i intensywnego wysiłku fizycznego. Stosujmy preparat pielęgnacyjny otrzymany w salonie. Po około 4 tygodniach zapraszamy na bezpłatną korektę, która pozwoli dopracować efekt.","text_en":"The first 7–10 days after the procedure are the key healing period. Avoid wetting the brows, saunas, tanning beds, and intense physical activity. Use the aftercare product provided by the salon. After about 4 weeks, we invite you for a free touch-up to perfect the result.","text_ru":"Первые 7–10 дней после процедуры — ключевой период заживления. Не мочите брови, избегайте сауны, солярия и интенсивных физических нагрузок. Используйте средство по уходу, полученное в салоне. Примерно через 4 недели приглашаем на бесплатную коррекцию."},
    {"id":"b1-9","type":"heading","level":"h2","text":"Najczęściej zadawane pytania","text_en":"Frequently asked questions","text_ru":"Часто задаваемые вопросы"},
    {"id":"b1-10","type":"heading","level":"h3","text":"Czy makijaż permanentny brwi boli?","text_en":"Does permanent eyebrow makeup hurt?","text_ru":"Больно ли делать перманентный макияж бровей?"},
    {"id":"b1-11","type":"text","text":"Dzięki zastosowaniu kremu znieczulającego zabieg jest praktycznie bezbolesny. Większość klientek opisuje odczucia jako lekkie draśnięcie.","text_en":"Thanks to numbing cream, the procedure is practically painless. Most clients describe the sensation as light scratching.","text_ru":"Благодаря обезболивающему крему процедура практически безболезненна. Большинство клиенток описывают ощущения как лёгкое царапание."},
    {"id":"b1-12","type":"heading","level":"h3","text":"Ile kosztuje makijaż permanentny brwi w Białymstoku?","text_en":"How much does permanent eyebrow makeup cost in Białystok?","text_ru":"Сколько стоит перманентный макияж бровей в Белостоке?"},
    {"id":"b1-13","type":"text","text":"Ceny w salonie Katarzyna Brui zaczynają się od 600 PLN za microblading i od 700 PLN za ombre brows. Cena obejmuje konsultację, zabieg i bezpłatną korektę po 4 tygodniach. Szczegółowy cennik znajdziesz na naszej stronie w zakładce Usługi.","text_en":"Prices at Katarzyna Brui salon start from 600 PLN for microblading and from 700 PLN for ombre brows. The price includes consultation, procedure, and a free touch-up after 4 weeks. See our Services page for full pricing.","text_ru":"Цены в салоне Katarzyna Brui начинаются от 600 PLN за микроблейдинг и от 700 PLN за омбре-брови. В цену входят консультация, процедура и бесплатная коррекция через 4 недели. Полный прайс-лист — на странице Услуги."},
    {"id":"b1-14","type":"heading","level":"h3","text":"Jak długo utrzymuje się efekt?","text_en":"How long do the results last?","text_ru":"Как долго держится эффект?"},
    {"id":"b1-15","type":"text","text":"Efekt makijażu permanentnego brwi utrzymuje się od 1 do 3 lat, w zależności od techniki, typu skóry i pielęgnacji. Microblading blaknie szybciej (12–18 miesięcy), natomiast powder brows mogą utrzymać się nawet do 3 lat.","text_en":"Permanent eyebrow makeup results last from 1 to 3 years, depending on technique, skin type, and aftercare. Microblading fades faster (12–18 months), while powder brows can last up to 3 years.","text_ru":"Результат перманентного макияжа бровей держится от 1 до 3 лет в зависимости от техники, типа кожи и ухода. Микроблейдинг бледнеет быстрее (12–18 месяцев), а пудровые брови могут держаться до 3 лет."},
    {"id":"b1-16","type":"heading","level":"h2","text":"Dlaczego warto wybrać salon Katarzyna Brui?","text_en":"Why choose Katarzyna Brui salon?","text_ru":"Почему стоит выбрать салон Katarzyna Brui?"},
    {"id":"b1-17","type":"text","text":"Nasz salon w Białymstoku to miejsce, gdzie pasja spotyka się z doświadczeniem. Katarzyna Brui to certyfikowana linergistka z wieloletnim stażem, która regularnie uczestniczy w szkoleniach i konferencjach branżowych. Używamy wyłącznie certyfikowanych, hipoalergicznych pigmentów. Każdy zabieg traktujemy indywidualnie — bo każda twarz jest wyjątkowa.","text_en":"Our salon in Białystok is where passion meets experience. Katarzyna Brui is a certified permanent makeup artist with years of expertise, regularly attending industry trainings and conferences. We use exclusively certified, hypoallergenic pigments. Every procedure is treated individually — because every face is unique.","text_ru":"Наш салон в Белостоке — это место, где страсть встречается с опытом. Katarzyna Brui — сертифицированный мастер перманентного макияжа с многолетним стажем. Мы используем только сертифицированные гипоаллергенные пигменты. Каждую процедуру мы выполняем индивидуально — потому что каждое лицо уникально."}
  ]'::jsonb,
  true,
  NOW(),
  7,
  10
),

-- 2. "makijaż permanentny ust Białystok cena" (650 searches/mo)
(
  'Makijaż permanentny ust w Białymstoku – cena, efekty i opinie',
  'Permanent Lip Makeup in Białystok – Price, Results and Reviews',
  'Перманентный макияж губ в Белостоке – цена, эффекты и отзывы',
  'makijaz-permanentny-ust-bialystok-cena',
  'tips',
  'Ile kosztuje makijaż permanentny ust w Białymstoku? Poznaj ceny, techniki i efekty zabiegu w salonie Katarzyna Brui. Naturalne, piękne usta bez codziennego malowania.',
  'How much does permanent lip makeup cost in Białystok? Discover prices, techniques and results at Katarzyna Brui salon.',
  'Сколько стоит перманентный макияж губ в Белостоке? Узнайте цены, техники и результаты в салоне Katarzyna Brui.',
  'Katarzyna Brui',
  ARRAY['makijaż permanentny ust Białystok', 'permanentne usta Białystok cena', 'makijaż permanentny ust cena', 'usta permanentne Białystok', 'aquarelle lips Białystok', 'permanentny kontur ust Białystok'],
  '[
    {"id":"b2-1","type":"heading","level":"h2","text":"Na czym polega makijaż permanentny ust?","text_en":"What is permanent lip makeup?","text_ru":"Что такое перманентный макияж губ?"},
    {"id":"b2-2","type":"text","text":"Makijaż permanentny ust to zabieg, który pozwala uzyskać piękny, naturalny kolor ust bez konieczności codziennego nakładania szminki. Pigment wprowadzany jest pod skórę, nadając ustom wyrazisty kontur, równomierny kolor i optycznie większą objętość. W salonie Katarzyna Brui w Białymstoku wykonujemy ten zabieg z najwyższą precyzją i dbałością o naturalny efekt.","text_en":"Permanent lip makeup is a procedure that gives you beautiful, natural lip color without daily lipstick application. Pigment is introduced under the skin, giving lips a defined contour, even color, and optically more volume. At Katarzyna Brui salon in Białystok, we perform this procedure with the highest precision and attention to natural results.","text_ru":"Перманентный макияж губ — это процедура, которая позволяет получить красивый естественный цвет губ без ежедневного нанесения помады. Пигмент вводится под кожу, придавая губам выразительный контур, ровный цвет и визуально больший объём."},
    {"id":"b2-3","type":"heading","level":"h2","text":"Techniki makijażu permanentnego ust","text_en":"Permanent lip makeup techniques","text_ru":"Техники перманентного макияжа губ"},
    {"id":"b2-4","type":"list","style":"bullet","items":["Aquarelle lips – akwarelowe usta z delikatnym przejściem kolorów. Efekt naturalnie podkreślonych ust. Najpopularniejsza technika w naszym salonie.","Full lip blush – pełne wypełnienie ust kolorem z delikatnym cieniowaniem. Idealny dla osób pragnących intensywniejszego efektu.","Kontur ust – subtelne podkreślenie kształtu ust. Polecany dla klientek, które chcą tylko poprawić obrys.","Kontur z cieniowaniem – połączenie wyrazistego konturu z delikatnym wypełnieniem. Złoty środek między naturalnością a wyrazistością."],"items_en":["Aquarelle lips – watercolor-style lips with gentle color transitions. Natural enhanced lip effect. Our salon''s most popular technique.","Full lip blush – full lip color fill with subtle shading. Perfect for those wanting a more intense result.","Lip liner – subtle lip shape enhancement. Recommended for clients who just want to improve the outline.","Liner with shading – combination of defined contour with gentle fill. The golden mean between natural and expressive."],"items_ru":["Акварельные губы – губы в акварельной технике с мягким переходом цветов. Эффект естественно подчёркнутых губ. Самая популярная техника в нашем салоне.","Полная заливка губ – полное заполнение губ цветом с мягкой растушёвкой. Идеально для тех, кто хочет более насыщенный эффект.","Контур губ – деликатное подчёркивание формы губ. Рекомендуется тем, кто хочет лишь улучшить очертания.","Контур с растушёвкой – сочетание выразительного контура с мягким заполнением."]},
    {"id":"b2-5","type":"heading","level":"h2","text":"Cennik makijażu permanentnego ust w Białymstoku","text_en":"Permanent lip makeup pricing in Białystok","text_ru":"Прайс-лист перманентного макияжа губ в Белостоке"},
    {"id":"b2-6","type":"text","text":"W salonie Katarzyna Brui w Białymstoku ceny makijażu permanentnego ust kształtują się następująco: aquarelle lips od 800 PLN, full lip blush od 900 PLN, kontur ust od 500 PLN, kontur z cieniowaniem od 700 PLN. Każda cena obejmuje konsultację indywidualną, zabieg oraz bezpłatną korektę po 4–6 tygodniach. To inwestycja na 2–3 lata pięknych ust bez codziennego makijażu.","text_en":"At Katarzyna Brui salon in Białystok, permanent lip makeup prices are: aquarelle lips from 800 PLN, full lip blush from 900 PLN, lip liner from 500 PLN, liner with shading from 700 PLN. Each price includes individual consultation, the procedure, and a free touch-up after 4–6 weeks.","text_ru":"В салоне Katarzyna Brui в Белостоке цены на перманентный макияж губ: акварельные губы от 800 PLN, полная заливка от 900 PLN, контур губ от 500 PLN, контур с растушёвкой от 700 PLN. Каждая цена включает консультацию, процедуру и бесплатную коррекцию через 4–6 недель."},
    {"id":"b2-7","type":"heading","level":"h2","text":"Jak wygląda zabieg krok po kroku?","text_en":"Step-by-step procedure","text_ru":"Как проходит процедура шаг за шагом?"},
    {"id":"b2-8","type":"list","style":"check","items":["Konsultacja i dobór koloru – wspólnie wybieramy odcień idealnie pasujący do karnacji","Rysowanie konturu – precyzyjne obrysowanie kształtu ust","Znieczulenie – nakładamy krem znieczulający na 15–20 minut","Pigmentacja – wprowadzanie pigmentu wybraną techniką (90–120 min)","Zalecenia pozabiegowe – szczegółowa instrukcja pielęgnacji","Korekta po 4–6 tygodniach – bezpłatne dopracowanie efektu"],"items_en":["Consultation and color selection – together we choose the perfect shade for your complexion","Contour drawing – precise lip shape outlining","Anesthesia – numbing cream applied for 15–20 minutes","Pigmentation – pigment application with chosen technique (90–120 min)","Aftercare instructions – detailed care guide","Touch-up after 4–6 weeks – free result perfection"],"items_ru":["Консультация и подбор цвета – вместе выбираем оттенок, идеально подходящий к тону кожи","Рисование контура – точное очерчивание формы губ","Анестезия – наносим обезболивающий крем на 15–20 минут","Пигментация – введение пигмента выбранной техникой (90–120 мин)","Рекомендации по уходу – подробная инструкция","Коррекция через 4–6 недель – бесплатная доработка результата"]},
    {"id":"b2-9","type":"heading","level":"h2","text":"Najczęściej zadawane pytania","text_en":"Frequently asked questions","text_ru":"Часто задаваемые вопросы"},
    {"id":"b2-10","type":"heading","level":"h3","text":"Ile kosztuje makijaż permanentny ust w Białymstoku?","text_en":"How much does permanent lip makeup cost in Białystok?","text_ru":"Сколько стоит перманентный макияж губ в Белостоке?"},
    {"id":"b2-11","type":"text","text":"Ceny makijażu permanentnego ust w Białymstoku wahają się od 500 do 1200 PLN w zależności od salonu i techniki. W salonie Katarzyna Brui ceny zaczynają się od 500 PLN za kontur, a najpopularniejsza technika aquarelle lips kosztuje od 800 PLN – w cenie konsultacja i korekta.","text_en":"Permanent lip makeup prices in Białystok range from 500 to 1200 PLN depending on the salon and technique. At Katarzyna Brui salon, prices start from 500 PLN for lip liner, and the most popular aquarelle lips technique costs from 800 PLN – consultation and touch-up included.","text_ru":"Цены на перманентный макияж губ в Белостоке варьируются от 500 до 1200 PLN в зависимости от салона и техники. В салоне Katarzyna Brui цены начинаются от 500 PLN за контур, а самая популярная техника акварельных губ стоит от 800 PLN — консультация и коррекция включены."},
    {"id":"b2-12","type":"heading","level":"h3","text":"Czy makijaż permanentny ust wygląda naturalnie?","text_en":"Does permanent lip makeup look natural?","text_ru":"Выглядит ли перманентный макияж губ естественно?"},
    {"id":"b2-13","type":"text","text":"Tak! Nowoczesne techniki, takie jak aquarelle lips, dają bardzo naturalny efekt. Kolor bezpośrednio po zabiegu jest intensywniejszy, ale po okresie gojenia (7–10 dni) blednie o 30–50% i wygląda jak delikatny, naturalny odcień.","text_en":"Yes! Modern techniques like aquarelle lips give a very natural result. The color right after the procedure is more intense, but after healing (7–10 days) it fades 30–50% and looks like a subtle, natural shade.","text_ru":"Да! Современные техники, такие как акварельные губы, дают очень естественный результат. Цвет сразу после процедуры более интенсивный, но после заживления (7–10 дней) бледнеет на 30–50% и выглядит как мягкий натуральный оттенок."},
    {"id":"b2-14","type":"heading","level":"h3","text":"Jak długo goi się makijaż permanentny ust?","text_en":"How long does permanent lip makeup take to heal?","text_ru":"Сколько заживает перманентный макияж губ?"},
    {"id":"b2-15","type":"text","text":"Pełne gojenie trwa około 4–6 tygodni. Przez pierwsze 3–5 dni usta mogą być opuchnięte i intensywnie kolorowe. Po tygodniu pojawia się złuszczanie – to normalny proces. Ostateczny kolor i efekt widoczny jest po około miesiącu.","text_en":"Full healing takes about 4–6 weeks. During the first 3–5 days, lips may be swollen and intensely colored. After a week, peeling occurs – this is normal. The final color and effect are visible after about a month.","text_ru":"Полное заживление занимает около 4–6 недель. В первые 3–5 дней губы могут быть отёчными и интенсивно окрашенными. Через неделю начинается шелушение — это нормальный процесс. Окончательный цвет и эффект виден примерно через месяц."}
  ]'::jsonb,
  true,
  NOW(),
  8,
  11
),

-- 3. "laminacja brwi Białystok efekt przed i po" (400 searches/mo)
(
  'Laminacja brwi w Białymstoku – efekt przed i po, cena, opinie',
  'Brow Lamination in Białystok – Before & After, Price, Reviews',
  'Ламинирование бровей в Белостоке – эффект до и после, цена, отзывы',
  'laminacja-brwi-bialystok-efekt-przed-i-po',
  'tips',
  'Laminacja brwi w Białymstoku – zobacz efekty przed i po, poznaj ceny i opinie klientek salonu Katarzyna Brui. Piękne, zaczesane brwi bez codziennej stylizacji!',
  'Brow lamination in Białystok – see before & after results, prices and reviews at Katarzyna Brui salon.',
  'Ламинирование бровей в Белостоке – смотрите эффекты до и после, цены и отзывы клиенток салона Katarzyna Brui.',
  'Katarzyna Brui',
  ARRAY['laminacja brwi Białystok', 'laminacja brwi efekt przed i po', 'laminacja brwi cena Białystok', 'brow lamination Białystok', 'laminacja brwi opinie', 'stylizacja brwi Białystok'],
  '[
    {"id":"b3-1","type":"heading","level":"h2","text":"Czym jest laminacja brwi?","text_en":"What is brow lamination?","text_ru":"Что такое ламинирование бровей?"},
    {"id":"b3-2","type":"text","text":"Laminacja brwi to jeden z najpopularniejszych zabiegów stylizacji brwi w Białymstoku. Polega na zmianie kierunku wzrostu włosków za pomocą specjalnych preparatów, co daje efekt zaczesanych, pełnych i idealnie ułożonych brwi. To doskonała alternatywa dla osób, które chcą piękne brwi bez makijażu permanentnego. W salonie Katarzyna Brui wykonujemy laminację z jednoczesnym botoksem brwiowym, który odżywia i wzmacnia włoski.","text_en":"Brow lamination is one of the most popular brow styling treatments in Białystok. It involves changing the growth direction of brow hairs using special formulas, creating a brushed-up, full, and perfectly styled look. It''s an excellent alternative for those who want beautiful brows without permanent makeup. At Katarzyna Brui salon, we perform lamination with brow botox that nourishes and strengthens the hairs.","text_ru":"Ламинирование бровей — одна из самых популярных процедур стайлинга бровей в Белостоке. Она заключается в изменении направления роста волосков с помощью специальных составов, что создаёт эффект зачёсанных, густых и идеально уложенных бровей."},
    {"id":"b3-3","type":"heading","level":"h2","text":"Efekt laminacji brwi – przed i po","text_en":"Brow lamination results – before and after","text_ru":"Эффект ламинирования бровей – до и после"},
    {"id":"b3-4","type":"text","text":"Efekt laminacji brwi jest widoczny natychmiast po zabiegu. Włoski zostają ułożone w pożądanym kierunku, brwi wyglądają na pełniejsze i bardziej uporządkowane. Różnica przed i po jest szczególnie widoczna u osób z niesfornymi, rosnącymi w różnych kierunkach włoskami. Efekt utrzymuje się przez 6–8 tygodni. W naszym salonie w Białymstoku łączymy laminację z henną brwiową lub koloryzacją, co potęguje efekt wow.","text_en":"The brow lamination effect is visible immediately after the procedure. Hairs are set in the desired direction, brows look fuller and more structured. The before-and-after difference is especially visible for those with unruly hairs growing in different directions. The effect lasts 6–8 weeks. At our Białystok salon, we combine lamination with brow henna or tinting for an enhanced wow effect.","text_ru":"Эффект ламинирования бровей виден сразу после процедуры. Волоски укладываются в нужном направлении, брови выглядят более густыми и упорядоченными. Эффект держится 6–8 недель."},
    {"id":"b3-5","type":"heading","level":"h2","text":"Ile kosztuje laminacja brwi w Białymstoku?","text_en":"How much does brow lamination cost in Białystok?","text_ru":"Сколько стоит ламинирование бровей в Белостоке?"},
    {"id":"b3-6","type":"text","text":"Cena laminacji brwi w salonie Katarzyna Brui w Białymstoku wynosi od 150 PLN. W pakiecie z henną brwiową lub koloryzacją cena zaczyna się od 180 PLN. Zabieg trwa około 45–60 minut i nie wymaga specjalnej pielęgnacji pozabiegowej – wystarczy unikać kontaktu z wodą przez 24 godziny.","text_en":"Brow lamination at Katarzyna Brui salon in Białystok costs from 150 PLN. In a package with brow henna or tinting, the price starts from 180 PLN. The treatment takes about 45–60 minutes and requires no special aftercare – just avoid water contact for 24 hours.","text_ru":"Цена ламинирования бровей в салоне Katarzyna Brui в Белостоке — от 150 PLN. В пакете с хной для бровей или окрашиванием цена начинается от 180 PLN."},
    {"id":"b3-7","type":"heading","level":"h2","text":"Dla kogo jest laminacja brwi?","text_en":"Who is brow lamination for?","text_ru":"Кому подходит ламинирование бровей?"},
    {"id":"b3-8","type":"list","style":"bullet","items":["Osoby z niesfornymi, trudnymi do ułożenia brwiami","Osoby z cienkimi włoskami, które chcą optycznie zagęścić brwi","Każdy, kto marzy o efekcie ''brushed brows'' znanym z Instagrama","Osoby szukające alternatywy dla makijażu permanentnego","Klientki, które chcą zaoszczędzić czas na poranną stylizację brwi"],"items_en":["Those with unruly, hard-to-style brows","Those with thin hairs who want optically fuller brows","Anyone dreaming of the Instagram-famous ''brushed brows'' effect","Those looking for an alternative to permanent makeup","Clients who want to save time on morning brow styling"],"items_ru":["Обладательницы непослушных, трудно укладываемых бровей","Обладательницы тонких волосков, желающие оптически уплотнить брови","Все, кто мечтает об эффекте ''brushed brows'' из Instagram","Те, кто ищет альтернативу перманентному макияжу","Клиентки, которые хотят сэкономить время на утреннюю укладку бровей"]},
    {"id":"b3-9","type":"heading","level":"h2","text":"Najczęściej zadawane pytania","text_en":"Frequently asked questions","text_ru":"Часто задаваемые вопросы"},
    {"id":"b3-10","type":"heading","level":"h3","text":"Jak długo utrzymuje się efekt laminacji brwi?","text_en":"How long does brow lamination last?","text_ru":"Как долго держится эффект ламинирования бровей?"},
    {"id":"b3-11","type":"text","text":"Efekt laminacji brwi utrzymuje się przez 6–8 tygodni. Trwałość zależy od indywidualnego cyklu wzrostu włosków i przestrzegania zaleceń pozabiegowych.","text_en":"Brow lamination results last 6–8 weeks. Duration depends on individual hair growth cycle and following aftercare instructions.","text_ru":"Эффект ламинирования бровей держится 6–8 недель. Длительность зависит от индивидуального цикла роста волосков."},
    {"id":"b3-12","type":"heading","level":"h3","text":"Czy laminacja brwi jest bezpieczna?","text_en":"Is brow lamination safe?","text_ru":"Безопасно ли ламинирование бровей?"},
    {"id":"b3-13","type":"text","text":"Tak, laminacja brwi wykonana w profesjonalnym salonie jest całkowicie bezpieczna. W salonie Katarzyna Brui używamy preparatów najwyższej jakości, delikatnych dla skóry i włosków. Jedynym przeciwwskazaniem jest alergia na składniki preparatów – dlatego zawsze wykonujemy test uczuleniowy.","text_en":"Yes, brow lamination performed in a professional salon is completely safe. At Katarzyna Brui salon, we use highest quality products that are gentle on skin and hairs. The only contraindication is allergy to product ingredients – that''s why we always perform a patch test.","text_ru":"Да, ламинирование бровей, выполненное в профессиональном салоне, полностью безопасно. В салоне Katarzyna Brui мы используем препараты высшего качества."},
    {"id":"b3-14","type":"heading","level":"h3","text":"Czy mogę łączyć laminację z henną brwiową?","text_en":"Can I combine lamination with brow henna?","text_ru":"Можно ли сочетать ламинирование с хной для бровей?"},
    {"id":"b3-15","type":"text","text":"Oczywiście! To jedno z najpopularniejszych połączeń w naszym salonie. Laminacja nadaje kształt i kierunek włoskom, a henna dodaje głębię koloru i optycznie zagęszcza brwi. Efekt jest spektakularny i utrzymuje się do 6 tygodni.","text_en":"Of course! It''s one of the most popular combinations at our salon. Lamination shapes and directs the hairs, while henna adds color depth and optically thickens the brows. The result is spectacular and lasts up to 6 weeks.","text_ru":"Конечно! Это одно из самых популярных сочетаний в нашем салоне. Ламинирование придаёт форму и направление волоскам, а хна добавляет глубину цвета."}
  ]'::jsonb,
  true,
  NOW(),
  6,
  12
),

-- 4. "przedłużanie rzęs Białystok cena i opinie" (1,100 searches/mo)
(
  'Przedłużanie rzęs w Białymstoku – cena, opinie i efekty',
  'Eyelash Extensions in Białystok – Price, Reviews and Results',
  'Наращивание ресниц в Белостоке – цена, отзывы и эффекты',
  'przedluzanie-rzes-bialystok-cena-opinie',
  'tips',
  'Szukasz przedłużania rzęs w Białymstoku? Sprawdź ceny, opinie klientek i efekty w salonie Katarzyna Brui. Metody 1:1, objętościowe i mega volume.',
  'Looking for eyelash extensions in Białystok? Check prices, client reviews and results at Katarzyna Brui salon.',
  'Ищете наращивание ресниц в Белостоке? Узнайте цены, отзывы клиенток и результаты в салоне Katarzyna Brui.',
  'Katarzyna Brui',
  ARRAY['przedłużanie rzęs Białystok', 'przedłużanie rzęs Białystok cena', 'przedłużanie rzęs opinie Białystok', 'rzęsy 1:1 Białystok', 'rzęsy objętościowe Białystok', 'mega volume rzęsy Białystok', 'stylizacja rzęs Białystok'],
  '[
    {"id":"b4-1","type":"heading","level":"h2","text":"Przedłużanie rzęs w Białymstoku – salon Katarzyna Brui","text_en":"Eyelash extensions in Białystok – Katarzyna Brui salon","text_ru":"Наращивание ресниц в Белостоке – салон Katarzyna Brui"},
    {"id":"b4-2","type":"text","text":"Przedłużanie rzęs to jeden z najchętniej wybieranych zabiegów kosmetycznych w Białymstoku. Piękne, długie i gęste rzęsy podkreślają spojrzenie i eliminują potrzebę codziennego makijażu oczu. W salonie Katarzyna Brui oferujemy pełen zakres metod przedłużania rzęs – od naturalnego efektu 1:1, przez objętościowe 2D–6D, aż po spektakularny mega volume.","text_en":"Eyelash extensions are one of the most popular cosmetic treatments in Białystok. Beautiful, long, and thick lashes enhance your look and eliminate the need for daily eye makeup. At Katarzyna Brui salon, we offer a full range of extension methods – from natural 1:1 effect, through 2D–6D volume, to spectacular mega volume.","text_ru":"Наращивание ресниц — одна из самых популярных косметических процедур в Белостоке. В салоне Katarzyna Brui мы предлагаем полный спектр методов наращивания ресниц."},
    {"id":"b4-3","type":"heading","level":"h2","text":"Metody przedłużania rzęs i ceny w Białymstoku","text_en":"Eyelash extension methods and prices in Białystok","text_ru":"Методы наращивания ресниц и цены в Белостоке"},
    {"id":"b4-4","type":"list","style":"bullet","items":["Metoda 1:1 (classic) – jedna sztuczna rzęsa na jedną naturalną. Naturalny, subtelny efekt. Cena: od 200 PLN. Czas zabiegu: ok. 90 min.","Metoda 2D–3D (light volume) – 2–3 cienkie rzęsy na jedną naturalną. Efekt delikatnej objętości. Cena: od 250 PLN. Czas: ok. 120 min.","Metoda 4D–6D (volume) – 4–6 ultracienkich rzęs na jedną naturalną. Pełna, efektowna objętość. Cena: od 300 PLN. Czas: ok. 150 min.","Mega volume (8D+) – powyżej 8 ultracienkich rzęs na jedną naturalną. Spektakularny, dramatyczny efekt. Cena: od 350 PLN. Czas: ok. 180 min.","Uzupełnienie (refill) – od 120 PLN (zalecane co 2–3 tygodnie)"],"items_en":["Classic 1:1 – one synthetic lash per natural lash. Natural, subtle effect. Price: from 200 PLN. Duration: approx. 90 min.","2D–3D (light volume) – 2–3 thin lashes per natural lash. Gentle volume effect. Price: from 250 PLN. Duration: approx. 120 min.","4D–6D (volume) – 4–6 ultra-thin lashes per natural lash. Full, dramatic volume. Price: from 300 PLN. Duration: approx. 150 min.","Mega volume (8D+) – 8+ ultra-thin lashes per natural lash. Spectacular, dramatic effect. Price: from 350 PLN. Duration: approx. 180 min.","Refill – from 120 PLN (recommended every 2–3 weeks)"],"items_ru":["Классика 1:1 – одна искусственная ресница на одну натуральную. Цена: от 200 PLN. Время: ок. 90 мин.","2D–3D (лёгкий объём) – 2–3 тонкие ресницы на одну натуральную. Цена: от 250 PLN. Время: ок. 120 мин.","4D–6D (объём) – 4–6 ультратонких ресниц на одну натуральную. Цена: от 300 PLN. Время: ок. 150 мин.","Мега-объём (8D+) – 8+ ультратонких ресниц. Цена: от 350 PLN. Время: ок. 180 мин.","Коррекция – от 120 PLN (каждые 2–3 недели)"]},
    {"id":"b4-5","type":"heading","level":"h2","text":"Co wyróżnia nasz salon w Białymstoku?","text_en":"What sets our Białystok salon apart?","text_ru":"Что отличает наш салон в Белостоке?"},
    {"id":"b4-6","type":"list","style":"check","items":["Certyfikowane stylistki z wieloletnim doświadczeniem","Najwyższej jakości rzęsy syntetyczne i jedwabne","Hipoalergiczne kleje – bezpieczne nawet dla wrażliwych oczu","Indywidualny dobór kształtu, długości i skrętu","Komfortowe warunki zabiegu – klimatyzowany gabinet","Darmowa konsultacja przed pierwszym zabiegiem"],"items_en":["Certified stylists with years of experience","Highest quality synthetic and silk lashes","Hypoallergenic adhesives – safe even for sensitive eyes","Individual selection of shape, length, and curl","Comfortable treatment conditions – air-conditioned room","Free consultation before the first treatment"],"items_ru":["Сертифицированные стилисты с многолетним опытом","Ресницы высшего качества","Гипоаллергенные клеи — безопасно для чувствительных глаз","Индивидуальный подбор формы, длины и изгиба","Комфортные условия","Бесплатная консультация перед первой процедурой"]},
    {"id":"b4-7","type":"heading","level":"h2","text":"Jak dbać o przedłużone rzęsy?","text_en":"How to care for eyelash extensions?","text_ru":"Как ухаживать за наращёнными ресницами?"},
    {"id":"b4-8","type":"text","text":"Aby cieszyć się pięknym efektem jak najdłużej, warto pamiętać o kilku zasadach: unikaj kontaktu z wodą przez pierwsze 24 godziny, nie stosuj kosmetyków olejowych w okolicy oczu, nie trzyj oczu, czesz rzęsy specjalną szczoteczką rano i wieczorem, przychodź na regularne uzupełnienia co 2–3 tygodnie.","text_en":"To enjoy beautiful results for as long as possible: avoid water contact for the first 24 hours, don''t use oil-based cosmetics near the eyes, don''t rub your eyes, brush lashes with a special spoolie morning and evening, come for regular refills every 2–3 weeks.","text_ru":"Чтобы наслаждаться красивым эффектом: избегайте воды первые 24 часа, не используйте масляные средства, не трите глаза, расчёсывайте ресницы щёточкой, приходите на коррекции каждые 2–3 недели."},
    {"id":"b4-9","type":"heading","level":"h2","text":"Najczęściej zadawane pytania","text_en":"Frequently asked questions","text_ru":"Часто задаваемые вопросы"},
    {"id":"b4-10","type":"heading","level":"h3","text":"Ile kosztuje przedłużanie rzęs w Białymstoku?","text_en":"How much do eyelash extensions cost in Białystok?","text_ru":"Сколько стоит наращивание ресниц в Белостоке?"},
    {"id":"b4-11","type":"text","text":"W salonie Katarzyna Brui ceny przedłużania rzęs w Białymstoku zaczynają się od 200 PLN za metodę classic 1:1. Objętościowe 2D–3D od 250 PLN, volume 4D–6D od 300 PLN, a mega volume od 350 PLN. Uzupełnienia od 120 PLN. Ceny obejmują konsultację i dobór stylu.","text_en":"At Katarzyna Brui salon, eyelash extension prices start from 200 PLN for classic 1:1. Volume 2D–3D from 250 PLN, 4D–6D from 300 PLN, mega volume from 350 PLN. Refills from 120 PLN.","text_ru":"В салоне Katarzyna Brui цены начинаются от 200 PLN за классику 1:1. Объём 2D–3D от 250 PLN, 4D–6D от 300 PLN, мега-объём от 350 PLN. Коррекции от 120 PLN."},
    {"id":"b4-12","type":"heading","level":"h3","text":"Czy przedłużanie rzęs niszczy naturalne rzęsy?","text_en":"Do eyelash extensions damage natural lashes?","text_ru":"Повреждает ли наращивание натуральные ресницы?"},
    {"id":"b4-13","type":"text","text":"Nie, jeśli zabieg jest wykonany profesjonalnie. W salonie Katarzyna Brui dobieramy grubość i długość sztucznych rzęs do możliwości naturalnych włosków. Nie obciążamy nadmiernie rzęs naturalnych, dzięki czemu zachowują swoją kondycję. Kluczowe jest regularne uzupełnianie i unikanie samodzielnego wyrywania rzęs.","text_en":"No, not when done professionally. We match synthetic lash thickness and length to your natural lashes'' capabilities, keeping them in good condition.","text_ru":"Нет, если процедура выполнена профессионально. Мы подбираем толщину и длину к возможностям натуральных ресниц."},
    {"id":"b4-14","type":"heading","level":"h3","text":"Jak często trzeba robić uzupełnienie rzęs?","text_en":"How often do lash refills need to be done?","text_ru":"Как часто нужно делать коррекцию ресниц?"},
    {"id":"b4-15","type":"text","text":"Zalecamy uzupełnienie co 2–3 tygodnie. Naturalne rzęsy mają swój cykl wzrostu i wypadają razem z przyklejonymi sztucznymi rzęsami. Regularne uzupełnienia pozwalają utrzymać pełny, piękny efekt bez przerw.","text_en":"We recommend refills every 2–3 weeks. Natural lashes have their growth cycle and fall out with attached synthetic lashes. Regular refills maintain the full effect.","text_ru":"Рекомендуем коррекцию каждые 2–3 недели. Регулярные коррекции поддерживают полный эффект."}
  ]'::jsonb,
  true,
  NOW(),
  7,
  13
);
